system:
  db-type: sqlite
  oss-type: local
  router-prefix: ""
  addr: 8888
jwt:
  signing-key: 'qwerty'
  expires-time: 7d
  buffer-time: 1d
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
sqlite:
  path: './data'
  db-name: 'core'