//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub mod prelude;

pub mod users;
pub mod user_setting;
pub mod system_setting;

pub mod word_records;
pub mod chapter_records;

pub mod dicts;
pub mod words;
