/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemErrorRouteImport } from './routes/system-error'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterAdminRouteImport } from './routes/register-admin'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ErrorsRouteImport } from './routes/errors'
import { Route as ContentRouteImport } from './routes/content'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistorySessionIdRouteImport } from './routes/history.$sessionId'

const SystemErrorRoute = SystemErrorRouteImport.update({
  id: '/system-error',
  path: '/system-error',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterAdminRoute = RegisterAdminRouteImport.update({
  id: '/register-admin',
  path: '/register-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorySessionIdRoute = HistorySessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => HistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/analysis': typeof AnalysisRoute
  '/articles': typeof ArticlesRoute
  '/content': typeof ContentRoute
  '/errors': typeof ErrorsRoute
  '/goals': typeof GoalsRoute
  '/history': typeof HistoryRouteWithChildren
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/register': typeof RegisterRoute
  '/register-admin': typeof RegisterAdminRoute
  '/settings': typeof SettingsRoute
  '/system-error': typeof SystemErrorRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/analysis': typeof AnalysisRoute
  '/articles': typeof ArticlesRoute
  '/content': typeof ContentRoute
  '/errors': typeof ErrorsRoute
  '/goals': typeof GoalsRoute
  '/history': typeof HistoryRouteWithChildren
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/register': typeof RegisterRoute
  '/register-admin': typeof RegisterAdminRoute
  '/settings': typeof SettingsRoute
  '/system-error': typeof SystemErrorRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/analysis': typeof AnalysisRoute
  '/articles': typeof ArticlesRoute
  '/content': typeof ContentRoute
  '/errors': typeof ErrorsRoute
  '/goals': typeof GoalsRoute
  '/history': typeof HistoryRouteWithChildren
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/register': typeof RegisterRoute
  '/register-admin': typeof RegisterAdminRoute
  '/settings': typeof SettingsRoute
  '/system-error': typeof SystemErrorRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/analysis'
    | '/articles'
    | '/content'
    | '/errors'
    | '/goals'
    | '/history'
    | '/login'
    | '/practice'
    | '/register'
    | '/register-admin'
    | '/settings'
    | '/system-error'
    | '/history/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/analysis'
    | '/articles'
    | '/content'
    | '/errors'
    | '/goals'
    | '/history'
    | '/login'
    | '/practice'
    | '/register'
    | '/register-admin'
    | '/settings'
    | '/system-error'
    | '/history/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/analysis'
    | '/articles'
    | '/content'
    | '/errors'
    | '/goals'
    | '/history'
    | '/login'
    | '/practice'
    | '/register'
    | '/register-admin'
    | '/settings'
    | '/system-error'
    | '/history/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AnalysisRoute: typeof AnalysisRoute
  ArticlesRoute: typeof ArticlesRoute
  ContentRoute: typeof ContentRoute
  ErrorsRoute: typeof ErrorsRoute
  GoalsRoute: typeof GoalsRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  LoginRoute: typeof LoginRoute
  PracticeRoute: typeof PracticeRoute
  RegisterRoute: typeof RegisterRoute
  RegisterAdminRoute: typeof RegisterAdminRoute
  SettingsRoute: typeof SettingsRoute
  SystemErrorRoute: typeof SystemErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system-error': {
      id: '/system-error'
      path: '/system-error'
      fullPath: '/system-error'
      preLoaderRoute: typeof SystemErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-admin': {
      id: '/register-admin'
      path: '/register-admin'
      fullPath: '/register-admin'
      preLoaderRoute: typeof RegisterAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$sessionId': {
      id: '/history/$sessionId'
      path: '/$sessionId'
      fullPath: '/history/$sessionId'
      preLoaderRoute: typeof HistorySessionIdRouteImport
      parentRoute: typeof HistoryRoute
    }
  }
}

interface HistoryRouteChildren {
  HistorySessionIdRoute: typeof HistorySessionIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistorySessionIdRoute: HistorySessionIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AnalysisRoute: AnalysisRoute,
  ArticlesRoute: ArticlesRoute,
  ContentRoute: ContentRoute,
  ErrorsRoute: ErrorsRoute,
  GoalsRoute: GoalsRoute,
  HistoryRoute: HistoryRouteWithChildren,
  LoginRoute: LoginRoute,
  PracticeRoute: PracticeRoute,
  RegisterRoute: RegisterRoute,
  RegisterAdminRoute: RegisterAdminRoute,
  SettingsRoute: SettingsRoute,
  SystemErrorRoute: SystemErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
